import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ChevronRight, Package, RefreshCw, Truck, CheckCircle2, Clock3 } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import api from '../../services/api';
import { getProductImage } from '../../utils/productImage';

const tabs = ['ALL', 'PLACED', 'ACCEPTED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED'];
const label = (status) => ({ PLACED: 'Order placed', ACCEPTED: 'Order accepted', PROCESSING: 'Being prepared', PACKED: 'Packed', SHIPPED: 'Shipped', OUT_FOR_DELIVERY: 'Out for delivery', DELIVERED: 'Delivered', CANCELLED: 'Cancelled' }[status] || status?.replaceAll('_', ' ') || 'Order placed');
function toDate(value) { if (!value) return null; if (typeof value?.toDate === 'function') return value.toDate(); const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; }
function formatDateTime(value) { const date = toDate(value); return date ? date.toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: true }) : 'Date unavailable'; }

export default function Orders() {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [orders, setOrders] = useState([]); const [tab, setTab] = useState('ALL'); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  async function load() { if (!user) return; setLoading(true); setError(''); try { const { data } = await api.get('/orders/mine'); setOrders(Array.isArray(data) ? data : []); } catch (e) { console.error(e); setError(e?.response?.data?.message || 'Unable to load your orders.'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [user]);
  const shown = useMemo(() => tab === 'ALL' ? orders : orders.filter((o) => o.orderStatus === tab || (tab === 'PROCESSING' && ['PROCESSING','PACKED'].includes(o.orderStatus)) || (tab === 'SHIPPED' && ['SHIPPED','OUT_FOR_DELIVERY'].includes(o.orderStatus))), [orders, tab]);
  return <section className="container-app py-6 sm:py-9 lg:py-12"><button className="back-link" onClick={() => navigate('/profile')}><ArrowLeft size={17}/> My Account</button><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="account-kicker"><Package size={14}/> Shopping history</p><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">My Orders</h1><p className="mt-2 text-sm text-stone-500">Track every pickle order from payment to doorstep.</p></div><button className="btn-secondary !px-4 !py-2.5" onClick={load} disabled={loading}><RefreshCw size={16} className={loading ? 'animate-spin' : ''}/> Refresh</button></div><div className="orders-tabs mt-7">{tabs.map((t) => <button key={t} onClick={() => setTab(t)} className={tab === t ? 'orders-tab-active' : ''}>{t === 'ALL' ? 'All' : t[0] + t.slice(1).toLowerCase()}</button>)}</div>{error && <div className="account-alert mt-5"><span>{error}</span></div>}{loading ? <div className="account-loading mt-6"><div className="loading-spinner"/> Loading your orders...</div> : !shown.length ? <div className="empty-account mt-6"><Package size={34}/><h2>{tab === 'ALL' ? 'No orders yet' : `No ${tab.toLowerCase()} orders`}</h2><p>Your completed purchases will appear here.</p><Link to="/products" className="btn-primary mt-3">Explore Pickles</Link></div> : <div className="mt-6 space-y-4">{shown.map((order) => <Link to={`/orders/${order.id}`} key={order.id} className="order-card"><div className="order-card-top"><div><span className="order-number">Order #{order.id.slice(-8).toUpperCase()}</span><span className="order-date">Ordered {formatDateTime(order.createdAt)}</span></div><span className={`order-status ${order.orderStatus === 'CANCELLED' ? 'order-status-cancelled' : order.orderStatus === 'DELIVERED' ? 'order-status-delivered' : ''}`}>{order.orderStatus === 'DELIVERED' ? <CheckCircle2 size={15}/> : order.orderStatus === 'SHIPPED' || order.orderStatus === 'OUT_FOR_DELIVERY' ? <Truck size={15}/> : <Clock3 size={15}/>} {label(order.orderStatus)}</span></div><div className="order-products">{(order.items || []).slice(0, 3).map((item, i) => <div key={`${item.productId}-${i}`} className="order-product"><img src={item.image || getProductImage({ id: item.productId, image: '' })} alt=""/><div className="min-w-0"><b className="line-clamp-2">{item.name}</b><span>{item.weight || 'Standard'} · Qty {item.quantity}</span></div></div>)}{(order.items || []).length > 3 && <span className="self-center text-xs font-bold text-stone-500">+{order.items.length - 3} more</span>}</div><div className="order-card-bottom"><div><span className="text-xs text-stone-500">Total amount</span><b className="mt-0.5 block text-lg">₹{order.total}</b></div><span className="order-view">View details <ChevronRight size={17}/></span></div></Link>)}</div>}</section>;
}
