import { useEffect, useState } from 'react';
import { RefreshCw, Star, Trash2 } from 'lucide-react';
import AdminLayout from '../../../components/admin/AdminLayout';
import api from '../../../services/api';
import { useToast } from '../../../context/ToastContext';
export default function AdminReviews(){
 const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true); const {showToast}=useToast();
 async function load(){setLoading(true);try{const {data}=await api.get('/admin/reviews');setRows(Array.isArray(data)?data:[]);}catch(e){showToast(e?.response?.data?.message||'Unable to load reviews.','error')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function toggle(row){try{const {data}=await api.patch(`/admin/reviews/${row.id}`,{approved:!row.approved,published:!row.approved});setRows(r=>r.map(x=>x.id===row.id?data:x));showToast('Review moderation updated.','success')}catch(e){showToast(e?.response?.data?.message||'Unable to update review.','error')}}
 async function remove(id){if(!confirm('Delete this review permanently?'))return;try{await api.delete(`/admin/reviews/${id}`);setRows(r=>r.filter(x=>x.id!==id));showToast('Review deleted.','success')}catch(e){showToast(e?.response?.data?.message||'Unable to delete review.','error')}}
 return <AdminLayout><div className="admin-page-head"><div><p className="account-kicker"><Star size={14}/> Customer voice</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Reviews</h1><p className="mt-2 text-sm text-stone-500">Approve genuine feedback and remove inappropriate submissions.</p></div><button className="btn-secondary" onClick={load} disabled={loading}><RefreshCw size={16} className={loading?'animate-spin':''}/> Refresh</button></div><div className="mt-7 grid gap-4">{rows.map(r=><article className="card p-5" key={r.id}><div className="flex flex-wrap items-start justify-between gap-4"><div><b>{r.name||r.userName||'Customer'}</b><p className="mt-1 text-xs text-stone-500">{r.email||r.userEmail||''}</p></div><div className="flex gap-2"><button className="btn-secondary !px-3 !py-2" onClick={()=>toggle(r)}>{r.approved||r.published?'Hide':'Approve'}</button><button className="rounded-xl border border-red-200 bg-red-50 px-3 py-2 font-bold text-red-700" onClick={()=>remove(r.id)}><Trash2 size={15}/></button></div></div><div className="mt-3 text-amber-600">{'★'.repeat(Math.min(5,Number(r.rating||5)))} <span className="ml-2 text-xs text-stone-400">{r.productName||r.product||''}</span></div><p className="mt-3 text-sm leading-6 text-stone-700">{r.comment||r.review||r.text||'No review text.'}</p><span className={`mt-4 inline-flex ${r.approved||r.published?'status-pill status-ok':'status-pill'}`}>{r.approved||r.published?'Published':'Pending'}</span></article>)}{!rows.length&&<div className="empty-account">{loading?'Loading reviews…':'No reviews yet.'}</div>}</div></AdminLayout>;
}
