import { useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { ChevronDown, SlidersHorizontal } from 'lucide-react';
import ProductGrid from '../../components/products/ProductGrid';
import api from '../../services/api';
const categories=['all','mango','lemon','chilli','garlic','mixed','special'];
export default function Products(){
 const [params]=useSearchParams(); const [sort,setSort]=useState('popular'); const [products,setProducts]=useState([]); const [loading,setLoading]=useState(true); const [category,setCategory]=useState(params.get('category')||'all'); const [mobileFilters,setMobileFilters]=useState(false); const [error,setError]=useState(''); const q=(params.get('q')||'').toLowerCase();
 async function load(){setLoading(true);setError('');try{const {data}=await api.get('/products');setProducts(Array.isArray(data)?data:[]);}catch(e){console.error(e);setProducts([]);setError('Unable to load the live catalogue. Please refresh and try again.');}finally{setLoading(false);}}
 useEffect(()=>{load();},[]); useEffect(()=>{setCategory(params.get('category')||'all');},[params]);
 const shown=useMemo(()=>{const x=products.filter(p=>(category==='all'||p.category===category)&&(!q||String(p.name||'').toLowerCase().includes(q)));if(sort==='priceLow')x.sort((a,b)=>Number(a.variants?.[0]?.price||0)-Number(b.variants?.[0]?.price||0));if(sort==='priceHigh')x.sort((a,b)=>Number(b.variants?.[0]?.price||0)-Number(a.variants?.[0]?.price||0));if(sort==='rating')x.sort((a,b)=>Number(b.rating||0)-Number(a.rating||0));return x;},[products,category,q,sort]);
 const label=category[0]?.toUpperCase()+category.slice(1);
 return <section className="container-app py-5 sm:py-8 lg:py-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.22em] text-achar-700 sm:text-sm">Shop</p><h1 className="mt-1.5 text-3xl font-black tracking-tight sm:text-4xl">Our Pickles</h1><p className="mt-2 text-sm text-stone-500">Live catalogue — prices and products come directly from the store.</p></div><div className="flex w-full gap-2 sm:w-auto"><button onClick={()=>setMobileFilters(v=>!v)} className="flex flex-1 items-center justify-between rounded-xl border border-stone-300 bg-white px-3 py-2.5 text-sm font-bold sm:hidden"><span className="flex items-center gap-2"><SlidersHorizontal size={17}/>{label}</span><ChevronDown size={17} className={mobileFilters?'rotate-180':''}/></button><select value={sort} onChange={e=>setSort(e.target.value)} className="input flex-1 py-2.5 text-sm sm:min-w-[165px] sm:flex-none"><option value="popular">Popular</option><option value="rating">Top Rated</option><option value="priceLow">Price: Low to High</option><option value="priceHigh">Price: High to Low</option></select></div></div>{mobileFilters&&<div className="mt-3 rounded-2xl border border-stone-200 bg-white p-3 shadow-sm sm:hidden"><div className="flex flex-wrap gap-2">{categories.map(c=><button key={c} onClick={()=>{setCategory(c);setMobileFilters(false)}} className={`rounded-full border px-3.5 py-2 text-xs font-bold ${category===c?'border-achar-700 bg-achar-700 text-white':'border-stone-200 bg-stone-50'}`}>{c[0].toUpperCase()+c.slice(1)}</button>)}</div></div>}<div className="mt-5 grid gap-6 lg:grid-cols-[190px_1fr] lg:gap-8"><aside className="card hidden h-fit p-3 lg:block"><h3 className="px-2 py-2 text-sm font-black uppercase tracking-wide">Categories</h3><div className="grid gap-0.5">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`rounded-xl px-3 py-2.5 text-left text-sm font-semibold ${category===c?'bg-amber-50 text-achar-700':'hover:bg-stone-50'}`}>{c[0].toUpperCase()+c.slice(1)}</button>)}</div></aside><div className="min-w-0"><div className="mb-4 flex items-center justify-between"><p className="text-sm font-semibold text-stone-500">{loading?'Loading products…':`${shown.length} products`}</p><button onClick={load} className="text-xs font-bold text-achar-700">Refresh</button></div>{loading?<div className="account-loading py-16"><div className="loading-spinner"/>Loading fresh catalogue…</div>:error?<div className="empty-account py-14"><p>{error}</p><button className="btn-primary mt-3" onClick={load}>Try again</button></div>:shown.length?<ProductGrid products={shown}/>:<div className="empty-account py-14"><h2>No pickles found</h2><p className="mt-1">This catalogue is currently empty for this filter.</p></div>}</div></div></section>;
}
